language: node_js
node_js:
  - "v14.15"

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
