--- 
addons: 
  chrome: stable
cache: 
  directories: 
    - node_modules
dist: trusty
language: node_js
node_js: 
  - "11.6.0"
.script: 
  - "npm run test"
  - "npm run build"
  - "xvfb-run npm run e2e"
sudo: false--- 


