--- 
addons: 
  chrome: stable
cache: 
  directories: 
    - node_modules
dist: trusty
language: node_js
node_js: 
  - "8"
script: 
  - "npm run lint"
  - "npm run test:headless"
  - "npm run build"
  - "xvfb-run npm run e2e"
sudo: false--- 
addons: 
  chrome: stable
cache: 
  directories: 
    - node_modules
dist: trusty
language: node_js
node_js: 
  - "8"
script: 
  - "npm run lint"
  - "npm run test:headless"
  - "npm run build"
  - "xvfb-run npm run e2e"
sudo: false
