--- 
Language: node_js
branch: master
cache: npm
deploy: ~
install: "npm install"
node_js: "12.14 "
provider: npm
script: 
  - "npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI"
  - "npm build"
skip-cleanup: true
true: ~

